bars_glob: "data/time_bars_1min/*/2025-0[16].parquet"   # forward slashes are cross-platform
price_col: "close"
# If your labeler needs to know the index name, set it (only if used by your script):
time_index_col: "t_last"
tz: "UTC"

# Labeling mode
mode: triple_barrier

# Triple-barrier label configuration (new keys)
vol_mode: atr                # atr | ewm_std
atr_window: 200              # ATR window length (bars)
atr_ma: ema                  # ema | sma
scale_with_sqrt_h: true      # scale barrier with sqrt(H)

# Horizons to label (minutes)
horizons_min: [120, 240, 480]

# Per-horizon multipliers (dict) or scalar fallback
k_pt: {120: 1.25, 240: 1.125, 480: 1.125}
k_sl: {120: 0.25, 240: 0.25, 480: 0.25}
timeout_label: 0

io:
  timebar_root: "data/time_bars_1min"
  out_dir: "data/labels_1min"
  skip_existing: true


regime:
  ema_spans: [30, 60, 120]
  slope_thr: 0.0
  vote_k_of_n: 2

cv:
  n_splits: 5
  embargo_minutes: 60

align:
  join_horizon: 240           # choose one of horizons for primary y
  join_mode: "floor_minute"   # floor micro t_last to minute then join
  regime_filter:
    mode: "feature"           # feature|filter
    min_votes: 2
