bars_glob: "data/time_bars_1min/*/2025-0[16].parquet"   # forward slashes are cross-platform
price_col: "close"
# If your labeler needs to know the index name, set it (only if used by your script):
time_index_col: "t_last"
horizons_min: [15, 60, 240]
pt_mult: 1.5
sl_mult: 1.0
max_horizon_min: 240
tz: "UTC"

io:
  timebar_root: "data/time_bars_1min"
  out_dir: "data/labels_1min"
  skip_existing: true

triple_barrier:
  horizons: [15, 30, 60]
  up_mult: 100.0
  dn_mult: 20.0
  vol_span: 60
  min_return: 0.0
  label_scheme: "onevsrest"   # onevsrest|trinary

regime:
  ema_spans: [30, 60, 120]
  slope_thr: 0.0
  vote_k_of_n: 2

cv:
  n_splits: 5
  embargo_minutes: 60

align:
  join_horizon: 30            # choose one of horizons for primary y
  join_mode: "floor_minute"   # floor micro t_last to minute then join
  regime_filter:
    mode: "feature"           # feature|filter
    min_votes: 2
