io:
  bar_type: "dollar"                # dollar|volume|tick|imbalance (for info_bars)
  info_root: "data/info_bars"       # used when source=info_bars
  out_dir: "data/micro_windows"
  skip_existing: false

build:
  window_len: 256                   # used indirectly via rolling/ewm history
  stride: 8
  dtype: "float32"
  features:
    - "logret_close"
    - "hl_range_norm"
    - "oc_spread_norm"
    - "vol_per_trade"
    - "bm_share"
    - "ewm_logret_16"
    - "ewm_abs_logret_16"
  ewm_spans:
    logret: 16

norm:
  method: "none"                    # Stage-3 raw; we standardize in merge step
  eps: 1.0e-8

runtime:
  months_per_job: 1
